name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libboost-all-dev \
            libfmt-dev \
            libtbb-dev \
            libgtest-dev \
            ninja-build \
            build-essential \
            cmake

      - name: Configure CMake
        run: |
          cmake -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_TESTING=ON

      - name: Build
        run: cmake --build build --config Release -j $(nproc)

      - name: Run Tests
        run: ctest --test-dir build --output-on-failure
