name: Documentation

on:
  push:
    branches: [main]
    paths:
      - "**/*.hpp"
      - "**/*.cpp"
      - "docs/**"
      - ".github/workflows/docs.yml"
  workflow_dispatch:

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Doxygen
        run: sudo apt-get install -y doxygen graphviz

      - name: Generate Documentation
        run: |
          cmake -B build -DBUILD_DOCS=ON
          cmake --build build --target docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/docs/html
